[versions]
agp = "8.13.2"
kotlin = "2.3.0"
bcprovJdk15to18Version = "1.78.1"
json = "20251224"
coreKtx = "1.17.0"
appcompat = "1.7.1"
kotlinReflect = "2.3.0"
material = "1.13.0"
ktor = "3.3.3"
jsoup = "1.21.2"
okhttp = "4.12.0"
desugarJdkLibs = "2.1.5"
junit4 = "4.13.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
bcpkix-jdk15to18 = { module = "org.bouncycastle:bcpkix-jdk15to18", version.ref = "bcprovJdk15to18Version" }
bcprov-jdk15to18-v1781 = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bcprovJdk15to18Version" }
json = { module = "org.json:json", version.ref = "json" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}